const drinkNames = { vi: ['Bàn trà', 'Bàn cà phê', 'Bàn thư'], en: ['Tea table', 'Coffee table', 'Letter table'] };
const drinkTypes = ['tea', 'coffee', 'letter'];
const letterFormCopy = {
  vi: { intro: 'Để lại đôi lời nhắn, hoặc giới thiệu cho mình một cuốn sách nhé!', open: 'Mở biểu mẫu Google', note: 'Biểu mẫu sẽ mở trong thẻ mới.' },
  en: { intro: 'Leave a note or recommend a book!', open: 'Open Google Form', note: 'The form will open in a new tab.' },
};
const drinkStories = {
  vi: [
    `<h3>Lịch sử & nguồn gốc</h3><p>Trà có lịch sử lâu đời, bắt nguồn từ Trung Quốc từ hàng nghìn năm trước rồi dần lan sang Nhật Bản, Hàn Quốc, Đông Nam Á, Trung Đông và châu Âu qua giao thương. Phần lớn các loại trà truyền thống đều làm từ cây <em>Camellia sinensis</em>, nhưng khác nhau ở cách chế biến và mức độ oxy hóa.</p><h3>Các loại trà</h3><dl><dt>Trà xanh</dt><dd>Gần như không oxy hóa, phổ biến ở Trung Quốc và Nhật Bản.</dd><dt>Trà trắng</dt><dd>Chế biến tối giản, thường dùng búp và lá non.</dd><dt>Trà ô long</dt><dd>Được oxy hóa một phần, nằm giữa trà xanh và trà đen.</dd><dt>Trà đen</dt><dd>Oxy hóa hoàn toàn, trở nên đặc biệt phổ biến ở Anh và châu Âu từ thế kỷ XVII–XIX.</dd><dt>Trà Phổ Nhĩ (Pu-erh)</dt><dd>Của Vân Nam, trải qua quá trình lên men và ủ lâu.</dd><dt>Trà thảo mộc</dt><dd>Các loại như trà hoa cúc, bạc hà hay rooibos thường được gọi là “trà thảo mộc”, nhưng về mặt thực vật học không phải trà thật vì không làm từ <em>Camellia sinensis</em>.</dd></dl>`,
    `<h3>Giống cà phê & cách pha</h3><p>Cà phê chủ yếu có <strong>hai giống thương mại lớn là Arabica và Robusta</strong>. <strong>Arabica</strong> thường thơm, vị thanh, chua rõ và ít đắng hơn; <strong>Robusta</strong> nhiều caffeine hơn, đậm, đắng và có body nặng hơn. Ngoài ra còn có <strong>Liberica</strong> với hương gỗ/trái cây khá đặc biệt và <strong>Excelsa</strong>, thường được dùng để tạo thêm độ phức tạp khi phối trộn.</p><p>Về cách pha, những kiểu phổ biến gồm <strong>espresso, americano, cappuccino, latte, flat white, filter/pour-over, French press, cold brew</strong> và <strong>cà phê phin Việt Nam</strong>.</p><h3>Độ cao & hương vị</h3><p>Một fact quan trọng là <strong>độ cao nơi trồng ảnh hưởng rất mạnh đến hương vị</strong>. Ở vùng cao, nhiệt độ thấp khiến quả cà phê chín chậm hơn, hạt thường đặc hơn và có nhiều hợp chất hương phức tạp; vì vậy cà phê vùng cao, đặc biệt Arabica, thường có <strong>độ chua sáng (acidity), hương hoa và trái cây rõ hơn</strong>. Ví dụ, cà phê Ethiopia hoặc Kenya trồng ở khoảng <strong>1.500–2.200 m</strong> thường có acidity cao hơn cà phê trồng ở vùng thấp.</p><p>Tuy nhiên, <strong>vĩ độ và độ cao tương tác với nhau</strong>: càng gần xích đạo thì thường phải trồng ở độ cao lớn hơn để có khí hậu mát phù hợp cho Arabica; càng xa xích đạo thì có thể trồng ở độ cao thấp hơn.</p><h3>Sơ chế & rang</h3><p>Ngoài độ cao, hương vị còn phụ thuộc vào <strong>giống cây, đất, lượng mưa, nhiệt độ, cách sơ chế và rang</strong>. Sơ chế <strong>washed</strong> thường cho vị sạch và acidity rõ; <strong>natural/dry</strong> thường ngọt, nhiều hương trái cây và đôi khi có cảm giác lên men; <strong>honey process</strong> nằm giữa hai kiểu này.</p><p>Rang <strong>light roast</strong> giữ được acidity và đặc điểm nguồn gốc nhiều hơn, còn <strong>dark roast</strong> làm giảm cảm nhận acidity và tăng vị đắng, caramel, chocolate hoặc smoky.</p><h3>Acidity không chỉ là vị chua</h3><p>Một điều thú vị nữa là từ “<strong>acidity</strong>” trong cà phê không đơn giản có nghĩa là “chua khó chịu”: trong specialty coffee, nó thường chỉ cảm giác tươi sáng như <strong>cam, chanh, táo, berry hoặc rượu vang</strong>.</p>`,
  ],
  en: [
    `<h3>History & origins</h3><p>Tea originated in China thousands of years ago, spreading through trade to Japan, Korea, Southeast Asia, the Middle East and Europe. Most traditional teas come from <em>Camellia sinensis</em>, differing in processing and oxidation.</p><h3>Types of tea</h3><dl><dt>Green tea</dt><dd>Almost unoxidized; popular in China and Japan.</dd><dt>White tea</dt><dd>Minimally processed, often using buds and young leaves.</dd><dt>Oolong</dt><dd>Partially oxidized, between green and black tea.</dd><dt>Black tea</dt><dd>Fully oxidized; especially popular in Britain and Europe from the seventeenth to nineteenth centuries.</dd><dt>Pu-erh</dt><dd>From Yunnan, undergoing fermentation and extended aging.</dd><dt>Herbal infusions</dt><dd>Chamomile, mint and rooibos are not botanically true teas because they do not come from <em>Camellia sinensis</em>.</dd></dl>`,
    `<h3>Varieties & brewing</h3><p>The two major commercial varieties are <strong>Arabica and Robusta</strong>. Arabica is typically fragrant, lighter, more acidic and less bitter. Robusta has more caffeine, stronger bitterness and a heavier body. <strong>Liberica</strong> has distinctive woody/fruity aromas; <strong>Excelsa</strong> adds complexity to blends.</p><p>Popular preparations include <strong>espresso, americano, cappuccino, latte, flat white, filter/pour-over, French press, cold brew</strong> and the <strong>Vietnamese phin</strong>.</p><h3>Altitude & flavor</h3><p><strong>Growing altitude strongly influences flavor.</strong> Cooler temperatures at higher elevations slow ripening. Beans are often denser and develop more complex aromatic compounds. High-altitude coffee, especially Arabica, often has brighter acidity and clearer floral and fruity notes. Ethiopian or Kenyan coffees grown at approximately <strong>1,500–2,200 m</strong> often have more acidity than lower-altitude coffees.</p><p><strong>Latitude and altitude interact:</strong> near the equator, Arabica generally needs higher elevations for a suitably cool climate; farther away, it may grow at lower elevations.</p><h3>Processing & roasting</h3><p>Flavor also depends on <strong>variety, soil, rainfall, temperature, processing and roasting</strong>. <strong>Washed</strong> processing often produces clean flavors and clear acidity; <strong>natural/dry</strong> processing often brings sweetness, fruitiness and sometimes fermented notes; <strong>honey processing</strong> falls between these styles.</p><p><strong>Light roasting</strong> preserves more acidity and origin character. <strong>Dark roasting</strong> reduces perceived acidity and increases bitterness and caramel, chocolate or smoky notes.</p><h3>What acidity means</h3><p>In specialty coffee, acidity does not simply mean unpleasant sourness: it often describes a bright, fresh sensation reminiscent of <strong>oranges, lemons, apples, berries or wine</strong>.</p>`,
  ],
};
const coffeeDetails = {
  vi: [
    { name: 'Arabica', description: 'Arabica (Coffea arabica) có nguồn gốc từ vùng cao Ethiopia. Cây thường phát triển tốt ở khí hậu mát và độ cao lớn hơn Robusta. Hạt Arabica thường có hương thơm rõ, độ chua sáng và vị đắng dịu, nhưng đặc điểm này thay đổi theo từng lô. Tùy giống cây, đất và cách sơ chế, tách cà phê có thể gợi hoa, cam chanh, quả mọng, chocolate hoặc các loại hạt. Hàm lượng caffeine trung bình thường thấp hơn Robusta. Cây khá nhạy cảm với nhiệt độ, sâu bệnh và biến động thời tiết. Arabica là một trong hai loài cung cấp phần lớn cà phê thương mại trên thế giới. Đặc điểm vùng trồng chỉ là gợi ý, vì cách sơ chế, rang và pha cũng ảnh hưởng mạnh đến hương vị.', preparations: 'Pour-over hoặc filter, drip và French press; cũng thường được dùng cho espresso, cappuccino và latte.', growingRegions: 'Brazil, Colombia và các nước khác ở Mỹ Latinh; Ethiopia và Kenya ở Đông Phi; cùng những vùng cao tại châu Á.', consumptionRegions: 'Được tiêu thụ trên toàn cầu, nổi bật trong thị trường cà phê đặc sản ở Bắc Mỹ, châu Âu, Nhật Bản và Hàn Quốc; đây là mô tả thị trường rộng, không phải bảng xếp hạng theo loài.' },
    { name: 'Robusta', description: 'Robusta là tên thường dùng cho các giống thuộc loài Coffea canephora. Loài này có nguồn gốc ở khu vực Tây và Trung Phi. Cây chịu nóng tốt và thường được trồng ở vùng thấp hơn Arabica. Cà phê Robusta thường có body dày, vị đắng rõ và hương gợi cacao, gỗ hoặc các loại hạt. Hàm lượng caffeine thường cao hơn Arabica, dù mức cụ thể còn tùy giống và cách đo. Robusta được dùng nhiều trong cà phê hòa tan và các blend cần thêm độ đậm hoặc lớp crema. Cây được trồng và sử dụng phổ biến ở Việt Nam, Indonesia, Ấn Độ, Uganda và Brazil. Đây là những liên hệ thường gặp chứ không phải quy tắc cố định về hương vị hay cách pha.', preparations: 'Cà phê phin Việt Nam, cà phê hòa tan và các blend espresso; cũng có thể pha bằng máy espresso hoặc French press.', growingRegions: 'Brazil, Việt Nam, Indonesia và Ấn Độ; Uganda cùng các nước khác ở Tây và Trung Phi.', consumptionRegions: 'Việt Nam và nhiều thị trường Đông Nam Á có các kiểu cà phê dùng Robusta; hạt này cũng phổ biến trong cà phê hòa tan và blend được tiêu thụ trên toàn cầu.' },
    { name: 'Liberica', description: 'Liberica (Coffea liberica) là một loài cà phê thương mại ít phổ biến hơn Arabica và Robusta. Loài này có nguồn gốc ở Tây Phi và được trồng tại một số vùng nhiệt đới nóng ẩm. Cây và quả thường lớn hơn những gì người uống quen thuộc ở Arabica. Hạt có kích thước lớn, hình dáng không đều và rãnh giữa đặc trưng. Hương vị thay đổi theo vùng, nhưng thường được mô tả là có nét gỗ, khói, hoa hoặc trái cây chín. Một số người nhận ra liên tưởng đến mít, song đây không phải đặc điểm có ở mọi mẻ cà phê. Liberica gắn với văn hóa cà phê ở Philippines và Malaysia, ngoài ra còn được trồng tại Indonesia. Sản lượng nhỏ khiến hạt này thường xuất hiện ở dạng cà phê vùng đơn lẻ hoặc trong các blend đặc biệt.', preparations: 'Cà phê lọc hoặc pour-over để cảm nhận hương riêng; cũng có thể pha theo kiểu cà phê truyền thống Philippines hoặc phối trộn.', growingRegions: 'Đông Nam Á, đặc biệt Philippines, Malaysia và Indonesia; loài này cũng có nguồn gốc và mọc ở các vùng nhiệt đới châu Phi.', consumptionRegions: 'Chủ yếu ở Đông Nam Á, nhất là Philippines, Malaysia và Indonesia; ngoài khu vực này thường là thị trường ngách với sản lượng tiêu thụ nhỏ.' },
    { name: 'Excelsa', description: 'Excelsa thường được xếp trong nhóm Liberica, với tên thực vật thường gặp là Coffea liberica var. dewevrei. Đây là loại cà phê hiếm hơn nhiều so với Arabica và Robusta. Cây được trồng với sản lượng nhỏ tại một số vùng nhiệt đới Đông Nam Á. Hương vị thường được mô tả là trái cây chín, chua sáng và có chiều sâu, nhưng thay đổi theo vùng trồng và cách rang. Một số nhà rang dùng Excelsa để tạo độ tương phản và tăng độ phức hợp cho blend. Hạt này cũng có thể được pha riêng để khám phá hương vị đặc trưng của từng mẻ. Cà phê Excelsa có thể dùng cho filter, pour-over hoặc cold brew, tùy mức rang và cách chế biến. Không có một công thức pha hay phong cách quốc gia duy nhất gắn riêng với Excelsa.', preparations: 'Filter, pour-over và cold brew; đôi khi được phối trộn cho espresso hoặc các blend cần thêm nét trái cây.', growingRegions: 'Một số vùng ở Việt Nam, Philippines và Ấn Độ; hoạt động trồng còn nhỏ và không đồng đều.', consumptionRegions: 'Chưa có thống kê tiêu thụ đáng tin cậy theo quốc gia; nhu cầu thương mại rất nhỏ. Phần lớn được dùng tại cộng đồng nơi trồng hoặc bán thành các lô đặc sản hạn chế.' },
  ],
  en: [
    { name: 'Arabica', description: 'Arabica (Coffea arabica) originated in the Ethiopian highlands. It generally grows well in cooler climates and at higher elevations than Robusta. Arabica often has a pronounced aroma, bright acidity and milder bitterness, though profiles vary by lot. Depending on cultivar, soil and processing, a cup may suggest flowers, citrus, berries, chocolate or nuts. Its caffeine content is usually lower than Robusta’s. The plant is relatively sensitive to temperature, pests and changing weather. Arabica is one of the two species that supply most of the world’s commercial coffee. Origin is only a guide, since processing, roasting and brewing also shape the final flavor.', preparations: 'Pour-over or filter, drip and French press; also widely used for espresso, cappuccino and latte.', growingRegions: 'Brazil, Colombia and other Latin American countries; Ethiopia and Kenya in East Africa; and higher-altitude areas of Asia.', consumptionRegions: 'Consumed worldwide, with a strong presence in specialty-coffee markets in North America, Europe, Japan and South Korea; this is a broad market pattern, not a species-by-species ranking.' },
    { name: 'Robusta', description: 'Robusta is a common name for varieties of the Coffea canephora species. The species is native to parts of western and central Africa. It tolerates heat well and is often grown at lower elevations than Arabica. Robusta coffee commonly has a heavier body, pronounced bitterness and notes that may suggest cocoa, wood or nuts. Its caffeine content is usually higher than Arabica’s, although the exact amount varies by variety and measurement. Robusta is widely used in instant coffee and blends that need extra strength or crema. It is commonly grown and consumed in Vietnam, Indonesia, India, Uganda and Brazil. These are broad associations, not fixed rules for flavor or brewing style.', preparations: 'Vietnamese phin coffee, instant coffee and espresso blends; it can also be brewed in an espresso machine or French press.', growingRegions: 'Brazil, Vietnam, Indonesia and India; Uganda and other countries in western and central Africa.', consumptionRegions: 'Vietnam and many Southeast Asian markets have familiar Robusta-based brews; it is also common in instant coffee and blends consumed worldwide.' },
    { name: 'Liberica', description: 'Liberica (Coffea liberica) is a commercial coffee species less common than Arabica or Robusta. It originated in West Africa and is cultivated in some hot, humid tropical regions. Its trees and cherries are often larger than those familiar from Arabica. The beans are large, irregular in shape and have a distinctive center crease. Flavor varies by origin, but is often described with woody, smoky, floral or ripe-fruit notes. Some drinkers notice a jackfruit-like character, though it is not present in every lot. Liberica is associated with coffee culture in the Philippines and Malaysia, and is also grown in Indonesia. Its limited production means it is often encountered as a regional single-origin coffee or in specialty blends.', preparations: 'Filter or pour-over to explore its distinct aromas; it can also be brewed in traditional Filipino styles or used in blends.', growingRegions: 'Southeast Asia, especially the Philippines, Malaysia and Indonesia; the species also originated in and grows in tropical Africa.', consumptionRegions: 'Mainly Southeast Asia, particularly the Philippines, Malaysia and Indonesia; elsewhere it remains a small niche market.' },
    { name: 'Excelsa', description: 'Excelsa is often grouped with Liberica, and is commonly referred to botanically as Coffea liberica var. dewevrei. It is much less common than Arabica or Robusta. It is grown in small quantities in some tropical parts of Southeast Asia. Its flavor is often described as ripe-fruited, bright and complex, but varies with origin and roast. Some roasters use Excelsa to add contrast and complexity to blends. It can also be brewed on its own to explore the character of a particular lot. Excelsa can be used for filter, pour-over or cold brew, depending on the roast and processing. No single brewing recipe or national coffee style is uniquely tied to Excelsa.', preparations: 'Filter, pour-over and cold brew; sometimes blended into espresso or coffees that benefit from fruity notes.', growingRegions: 'Some regions of Vietnam, the Philippines and India; cultivation remains small and uneven.', consumptionRegions: 'Reliable country-level consumption statistics are not available, and commercial demand is very small. Most is consumed locally where it is grown or sold in limited specialty lots.' },
  ],
};
const coffeeSources = [
  [{ name: 'Britannica', url: 'https://www.britannica.com/topic/coffee' }],
  [
    { name: 'Britannica', url: 'https://www.britannica.com/topic/coffee' },
    { name: 'Perfect Daily Grind', url: 'https://perfectdailygrind.com/2019/10/can-fine-robusta-be-considered-quality-coffee/' },
  ],
  [{ name: 'Perfect Daily Grind', url: 'https://perfectdailygrind.com/2020/11/what-is-coffea-liberica/' }],
  [{ name: 'Perfect Daily Grind', url: 'https://perfectdailygrind.com/2021/05/what-is-excelsa-coffee/' }],
];
const drinkDialog = document.querySelector('#drink-dialog');
const teaDetails = Object.fromEntries(Object.entries(drinkStories).map(([language, stories]) => {
  const document = new DOMParser().parseFromString(stories[0], 'text/html');
  return [language, [...document.querySelectorAll('dt')].map(title => ({ name: title.textContent, description: title.nextElementSibling.innerHTML }))];
}));
const teaHistories = {
  vi: [
    'Trà xanh có nguồn gốc từ Trung Quốc, nơi văn hóa uống trà phát triển qua nhiều thế kỷ. Dưới thời Đường, trà thường được hấp và ép thành bánh, khác với nhiều dạng trà lá rời ngày nay. Các nhà sư góp phần đưa văn hóa trà từ Trung Quốc sang Nhật Bản. Lá được làm nóng sớm sau khi hái để hạn chế hoạt động của enzyme gây oxy hóa. Nhiều loại trà xanh Nhật Bản dùng phương pháp hấp, còn nhiều loại của Trung Quốc được sao trong chảo. Matcha là trà xanh nghiền mịn, nên người uống dùng cả phần bột lá thay vì chỉ nước ngâm. Trà xanh hấp kiểu Nhật thường gợi cỏ non hoặc rong biển, trong khi trà sao chảo của Trung Quốc có thể thơm hạt rang. Độ chua tươi và vị chát se là hai cảm giác khác nhau khi nếm trà. Ngâm lá quá lâu hoặc dùng nước quá nóng có thể làm vị đắng, chát lấn át hương thơm.',
    'Trà trắng gắn liền với tỉnh Phúc Kiến của Trung Quốc, đặc biệt là những vùng như Phúc Đỉnh và Chính Hòa. Tên gọi thường liên quan đến lớp lông trắng bạc phủ trên búp non. Không phải mọi loại trà trắng đều chỉ gồm búp, vì một số loại dùng cả lá. Quy trình thường dựa vào làm héo và sấy khô, với ít công đoạn hơn nhiều nhóm trà khác. Trong lúc làm héo, lá vẫn có thể oxy hóa nhẹ, nên trà trắng không hoàn toàn không oxy hóa. Trà Ngân Châm nổi tiếng với những búp dài phủ lông bạc, còn Bạch Mẫu Đơn thường kết hợp búp và lá non. Hương trà trắng thường nhẹ, có thể gợi hoa, mật ong hoặc trái cây khô, nhưng không phải mẻ nào cũng có các nốt này. Độ chua thanh và cảm giác se miệng từ polyphenol là hai nét khác nhau khi nếm. Ngâm bằng nước dịu hơn và rót qua nhiều lượt ngắn có thể giúp nhận ra các tầng hương tinh tế.',
    'Trà ô long phát triển trong truyền thống làm trà của Phúc Kiến, Trung Quốc. Sau đó, kỹ thuật này lan đến những vùng khác và trở thành một nét nổi bật của văn hóa trà Đài Loan. Tên ô long thường được dịch là rồng đen. Người làm trà kiểm soát quá trình làm héo, đảo lá và oxy hóa trước khi dùng nhiệt để dừng biến đổi. Mức oxy hóa và cách rang rất khác nhau, nên ô long có thể mang hương hoa nhẹ hoặc hương rang sâu. Một số loại được cuộn thành viên, trong khi những loại khác giữ hình lá dài xoắn. Ô long oxy hóa nhẹ thường nghiêng về hương hoa và trái cây, còn loại rang đậm có thể gợi hạt rang hoặc caramel. Một số ô long vùng cao có độ chua tươi, nhưng vị chua không phải dấu hiệu duy nhất của chất lượng. Pha nhiều lượt ngắn có thể làm mỗi lần rót mở ra một lớp hương khác.',
    'Trà đen phát triển ở Trung Quốc rồi lan rộng qua các tuyến thương mại quốc tế. Tại Trung Quốc, nhóm này được gọi là hồng trà, theo màu nước pha chứ không phải màu lá khô. Trà trở nên quen thuộc ở Anh từ thế kỷ XVII và phổ biến rộng hơn trong những thế kỷ tiếp theo. Việc trồng trà quy mô lớn ở Ấn Độ và Sri Lanka trong thế kỷ XIX góp phần mở rộng nguồn cung. Lá thường được làm héo, vò, oxy hóa rồi sấy khô để tạo màu và hương đặc trưng. Assam, Darjeeling và Ceylon là những tên nguồn gốc nổi tiếng, nhưng hương vị còn thay đổi theo mùa hái và cách chế biến. Trà Assam thường gợi mạch nha, trong khi một số trà Darjeeling có hương hoa hoặc nho muscat. Độ chua tươi, vị chát và vị đắng là các cảm giác khác nhau, dù có thể xuất hiện cùng lúc. Ngâm lá lâu hơn thường chiết xuất vị mạnh hơn và có thể làm vị đắng, chát rõ hơn.',
    'Trà Phổ Nhĩ gắn với tỉnh Vân Nam, Trung Quốc, và lấy tên từ địa danh Phổ Nhĩ. Trà từ vùng này từng được vận chuyển qua những mạng lưới giao thương thường gọi là con đường Trà Mã. Ép trà thành bánh giúp việc đóng gói và vận chuyển thuận tiện hơn. Phổ Nhĩ sống biến đổi dần trong quá trình lưu trữ, với sự tham gia của các phản ứng hóa học và vi sinh vật. Phổ Nhĩ chín dùng kỹ thuật ủ đống ẩm được phát triển trong thập niên 1970 để thúc đẩy quá trình biến đổi. Tuổi trà không tự bảo đảm chất lượng, vì nguyên liệu và điều kiện bảo quản cũng rất quan trọng. Phổ Nhĩ sống có thể phát triển hương trái cây khô hoặc gỗ theo thời gian, nhưng điều đó còn tùy nguyên liệu và cách lưu trữ. Phổ Nhĩ chín thường có hương đất dịu, khác với mùi ẩm mốc không mong muốn. Độ chua, chát và đắng còn thay đổi theo loại trà, cách bảo quản và thời gian ngâm.',
    'Việc ngâm lá, hoa và rễ cây trong nước đã xuất hiện trong nhiều nền văn hóa từ lâu. Hoa cúc và bạc hà có lịch sử sử dụng lâu đời ở những vùng quanh Địa Trung Hải và Trung Đông. Rooibos gắn với vùng Cederberg của Nam Phi và được làm từ cây Aspalathus linearis. Rooibos đỏ trải qua oxy hóa trong chế biến, còn rooibos xanh được xử lý để hạn chế quá trình này. Hoa cúc, bạc hà và rooibos nguyên chất tự nhiên không có caffeine, nhưng hỗn hợp có trà thật có thể chứa caffeine. Tên gọi trà thảo mộc bao phủ rất nhiều loài cây, nên độ an toàn và cách dùng phải được xem xét theo từng thành phần. Hoa cúc thường có hương dịu như táo hoặc hoa, còn rooibos có thể gợi mật ong và gỗ. Độ chua phụ thuộc vào loại cây, chẳng hạn hibiscus thường cho nước pha chua thanh hơn hoa cúc. Vị chua từ hibiscus là cảm nhận hương vị, còn độ chát se đến từ các hợp chất khác trong nguyên liệu.',
  ],
  en: [
    'Green tea originated in China, where tea culture developed over many centuries. During the Tang dynasty, tea was often steamed and pressed into cakes, unlike many loose-leaf forms today. Buddhist monks helped bring Chinese tea culture to Japan. Leaves are heated early after picking to limit the enzymes responsible for oxidation. Many Japanese green teas are steamed, while many Chinese varieties are pan-fired. Matcha is finely ground green tea, so the drinker consumes the powdered leaf rather than only an infusion. Steamed Japanese green teas can suggest fresh grass or seaweed, while pan-fired Chinese teas may smell nutty or toasted. Bright acidity and drying astringency are distinct sensations when tasting tea. Over-steeping or using water that is too hot can make bitterness and astringency overshadow the aroma.',
    'White tea is closely associated with Fujian province in China, particularly Fuding and Zhenghe. Its name often refers to the silvery hairs covering young buds. Not every white tea consists only of buds, as some varieties also contain leaves. Processing usually relies on withering and drying, with fewer steps than many other tea categories. Some oxidation can occur during withering, so white tea is not entirely unoxidized. Silver Needle is known for its long, downy buds, while White Peony usually combines buds and young leaves. White tea often has a delicate aroma that may suggest flowers, honey or dried fruit, though not every lot shows these notes. Bright acidity and the drying sensation from polyphenols are different aspects of its taste. Gentler water and several short infusions can help reveal its subtle layers of aroma.',
    'Oolong developed within the tea-making traditions of Fujian in China. Its techniques later spread elsewhere and became an important part of Taiwanese tea culture. The name oolong is commonly translated as black dragon. Producers control withering, agitation and oxidation before applying heat to stop the changes. Oxidation levels and roasting styles vary widely, producing anything from light floral aromas to deeper roasted notes. Some varieties are rolled into balls, while others retain long, twisted leaves. Lightly oxidized oolongs often lean toward floral and fruity aromas, while darker roasts may suggest toasted nuts or caramel. Some high-grown oolongs have a bright acidity, but sourness alone is not a measure of quality. Several short infusions can reveal a different layer of aroma with each pour.',
    'Black tea developed in China and spread through international trade routes. In China it is called red tea, referring to the infusion rather than the dry leaves. Tea became familiar in Britain during the seventeenth century and more widespread in the following centuries. Large-scale cultivation in India and Sri Lanka during the nineteenth century expanded supplies. Leaves are usually withered, rolled, oxidized and dried to develop their characteristic color and aroma. Assam, Darjeeling and Ceylon are famous origin names, but flavor also varies with harvest season and processing. Assam tea often suggests malt, while some Darjeeling teas have floral or muscat-like aromas. Bright acidity, astringency and bitterness are distinct sensations, though they can appear together. Longer steeping usually extracts a stronger cup and can make bitterness and astringency more noticeable.',
    'Pu-erh is associated with Yunnan province in China and takes its name from the place called Pu-erh. Tea from this region traveled along trade networks commonly known as the Tea Horse Road. Pressing tea into cakes made packing and transport more convenient. Raw pu-erh changes gradually during storage through chemical reactions and microbial activity. Ripe pu-erh uses a moist piling technique developed in the 1970s to accelerate these transformations. Age alone does not guarantee quality, because the raw material and storage conditions also matter. Raw pu-erh may develop dried-fruit or woody aromas over time, depending on its leaves and storage. Ripe pu-erh often has mellow earthy notes, which are different from unwanted mustiness. Acidity, astringency and bitterness vary with the tea, storage and steeping method.',
    'Infusing leaves, flowers and roots in water has a long history across many cultures. Chamomile and mint have longstanding traditions of use around the Mediterranean and the Middle East. Rooibos is associated with the Cederberg region of South Africa and comes from Aspalathus linearis. Red rooibos undergoes oxidation during processing, while green rooibos is processed to limit it. Pure chamomile, mint and rooibos are naturally caffeine-free, but blends containing true tea can contain caffeine. Herbal tea covers many different plants, so safety and appropriate use depend on the individual ingredients. Chamomile often has a gentle apple-like or floral aroma, while rooibos can suggest honey and wood. Acidity depends on the plant, and hibiscus usually makes a tarter infusion than chamomile. Hibiscus tartness is a flavor impression, while drying astringency comes from different compounds in the ingredients.',
  ],
};
const teaSources = [
  [{ name: 'Britannica', url: 'https://www.britannica.com/topic/tea-beverage' }],
  [{ name: 'Britannica', url: 'https://www.britannica.com/topic/tea-beverage' }],
  [{ name: 'Britannica', url: 'https://www.britannica.com/topic/tea-beverage' }],
  [{ name: 'Britannica', url: 'https://www.britannica.com/topic/tea-beverage' }],
  [{ name: 'Puer Tea (UW Press)', url: 'https://uwapress.uw.edu/book/9780295993232/puer-tea/' }],
  [
    { name: 'UKTIA', url: 'https://www.tea.co.uk/about/infusions' },
    { name: 'NIH: Chamomile', url: 'https://www.nccih.nih.gov/health/chamomile' },
    { name: 'NIH: Peppermint', url: 'https://www.nccih.nih.gov/health/peppermint-oil' },
  ],
];
let selectedDrink = null;
let selectedTea = null;
let selectedCoffee = null;
function renderDrink() {
  if (selectedCoffee !== null) {
    const coffee = coffeeDetails[uiLanguage][selectedCoffee];
    const english = uiLanguage === 'en';
    const sources = coffeeSources[selectedCoffee].map(source => `<a href="${source.url}" target="_blank" rel="noopener noreferrer">${source.name}</a>`).join(' · ');
    const consumptionNote = english ? 'Species-specific consumption data is limited; these regions describe common market patterns, not a ranked dataset.' : 'Số liệu tiêu thụ theo từng loài còn hạn chế; các vùng dưới đây mô tả tập quán thị trường, không phải bảng xếp hạng.';
    document.querySelector('#drink-content').innerHTML = `<h2 id="drink-title">${coffee.name}</h2><div class="drink-copy" lang="${uiLanguage}"><p>${coffee.description}</p><h3>${english ? 'Common preparations' : 'Cách pha thường gặp'}</h3><p>${coffee.preparations}</p><h3>${english ? 'Major growing regions' : 'Vùng trồng nhiều'}</h3><p>${coffee.growingRegions}</p><h3>${english ? 'Common consumption regions' : 'Vùng tiêu thụ phổ biến'}</h3><p>${coffee.consumptionRegions}</p><small class="drink-source">${english ? 'Reference' : 'Nguồn tham khảo'}: ${sources}</small><small class="drink-source">${consumptionNote}</small></div>`;
    return;
  }
  if (selectedTea !== null) {
    const tea = teaDetails[uiLanguage][selectedTea];
    const sources = teaSources[selectedTea].map(source => `<a href="${source.url}" target="_blank" rel="noopener noreferrer">${source.name}</a>`).join(' · ');
    document.querySelector('#drink-content').innerHTML = `<h2 id="drink-title">${tea.name}</h2><div class="drink-copy" lang="${uiLanguage}"><p>${tea.description}</p><p>${teaHistories[uiLanguage][selectedTea]}</p><small class="drink-source">${uiLanguage === 'en' ? 'Reference' : 'Nguồn tham khảo'}: ${sources}</small></div>`;
    return;
  }
  if (selectedDrink === null) return;
  if (drinkTypes[selectedDrink] === 'letter') {
    const copy = letterFormCopy[uiLanguage];
    document.querySelector('#drink-content').innerHTML = `<h2 id="drink-title">${drinkNames[uiLanguage][selectedDrink]}</h2><div class="drink-copy" lang="${uiLanguage}"><p>${copy.intro}</p><a class="letter-form-link" href="https://forms.gle/GMP1oha2SUt8xXtg6" target="_blank" rel="noopener noreferrer">${copy.open}</a><small class="letter-note">${copy.note}</small></div>`;
    return;
  }
  document.querySelector('#drink-content').innerHTML = `<h2 id="drink-title">${drinkNames[uiLanguage][selectedDrink]}</h2><div class="drink-copy" lang="${uiLanguage}">${drinkStories[uiLanguage][selectedDrink]}</div>`;
}
function refreshDrinks() {
  const english = uiLanguage === 'en';
  document.querySelector('#room-nav').textContent = english ? 'The room' : 'Phòng đọc sách';
  document.querySelector('#drinks-nav').textContent = english ? 'Tea & coffee' : 'Phòng trà & cà phê';
  document.querySelector('#drinks-title').textContent = english ? 'Tea & coffee room' : 'Phòng trà & cà phê';
  document.querySelector('#drinks-eyebrow').textContent = english ? 'A SIP, A STORY' : 'MỘT NGỤM, MỘT CÂU CHUYỆN';
  document.querySelectorAll('[data-drink-label]').forEach(label => { label.textContent = drinkNames[uiLanguage][drinkTypes.indexOf(label.dataset.drinkLabel)]; });
  document.querySelectorAll('[data-tea]').forEach(button => {
    const name = teaDetails[uiLanguage][Number(button.dataset.tea)].name;
    button.title = name;
    button.querySelector('.tea-name').textContent = name;
  });
  document.querySelectorAll('[data-coffee]').forEach(button => {
    const name = coffeeDetails[uiLanguage][Number(button.dataset.coffee)].name;
    button.title = name;
    button.querySelector('.coffee-name').textContent = name;
  });
  const close = document.querySelector('#close-drink');
  close.title = english ? 'Close' : 'Đóng';
  close.setAttribute('aria-label', close.title);
  renderDrink();
}
document.querySelectorAll('[data-drink]').forEach(button => button.addEventListener('click', () => {
  selectedTea = null;
  selectedCoffee = null;
  selectedDrink = drinkTypes.indexOf(button.dataset.drink);
  renderDrink();
  drinkDialog.showModal();
  document.body.style.overflow = 'hidden';
}));
document.querySelectorAll('[data-tea]').forEach(button => button.addEventListener('click', () => {
  selectedDrink = null;
  selectedCoffee = null;
  selectedTea = Number(button.dataset.tea);
  renderDrink();
  drinkDialog.showModal();
  document.body.style.overflow = 'hidden';
}));
document.querySelectorAll('[data-coffee]').forEach(button => button.addEventListener('click', () => {
  selectedDrink = null;
  selectedTea = null;
  selectedCoffee = Number(button.dataset.coffee);
  renderDrink();
  drinkDialog.showModal();
  document.body.style.overflow = 'hidden';
}));
document.querySelector('#close-drink').addEventListener('click', () => drinkDialog.close());
drinkDialog.addEventListener('close', () => { selectedDrink = null; selectedTea = null; selectedCoffee = null; document.body.style.overflow = ''; });
drinkDialog.addEventListener('click', event => {
  if (event.target !== drinkDialog) return;
  const bounds = drinkDialog.getBoundingClientRect();
  if (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom) drinkDialog.close();
});
document.addEventListener('languagechange', refreshDrinks);
refreshDrinks();